### PR TITLE
Add: Strategic map for re-deployment

### PR DESCRIPTION
**Pull request by Vdauphin**
https://github.com/Vdauphin/HeartsAndMinds/issues/188
https://forums.bistudio.com/topic/196594-strategicmap-is-dark/?p=3109122
https://feedback.bistudio.com/T120739

Final test :
- [x] local
- [x] server

Here is a vanilla mission to test strategic map : [tempMissionMP.Altis.pbo.zip](https://github.com/Vdauphin/HeartsAndMinds/files/548774/tempMissionMP.Altis.pbo.zip)

here is the short code to display strategic map : 

```
([] call bis_fnc_displayMission) createdisplay "RscDisplayStrategicMapSimulation"; 
_display = finddisplay 506; 
_fade = _display displayctrl 1099; 
_fade ctrlsetfade 1; 
_fade ctrlcommit 2;
```

Before 1.70

Since 1.70

### CODE REVIEW

**Comment by Breech99** [comment]
I found some issue with the redeploy script where it brings up the strategic map, click confirm to teleport to a named FOB, but then sends player to respawn_west location.  I wonder what's causing that, maybe specifically name the FOB and then have it look for an array of named FOBs? not sure. Works in other missions that way.

**Comment by Vdauphin** [comment]
I prefer to not go deeper due to the darkness of the strategic map :/
see https://forums.bistudio.com/topic/196594-strategicmap-is-dark/?p=3109122

**Comment by Vdauphin** [comment]
Do you have the same issue ?

**Comment by Breech99** [comment]
Yes, and I cannot redeploy at anything but the respawn_west position. It's too bad BI decided to do a dark alpha overlay on the S map. Seems like a bad idea especially for night ops.

**Comment by Breech99** [comment]
Yes I have the same issue. screen is dark and the redeploy doesn't work. It continues to send me to respawn_west only and not any FOB points.
 

    On Tuesday, October 25, 2016 2:18 AM, Vdauphin <notifications@github.com> wrote:
 

 Do you have the same issue ?—

**Comment by Breech99** [comment]
YES!! Teleporting works. Good find. I think the finddisplay and displayctrl numbers are ID numbers and don't adjust display. I could be wrong. I'll have to check the biki again.

**Comment by Vdauphin** [comment]
https://feedback.bistudio.com/T120739

**Pull request merged**
