### PR TITLE
Add: Tag abandoned vehicles

### PR DESCRIPTION
**Pull request by Vdauphin**
- Add: Tag abandoned vehicles (@Vdauphin).

**When merged this pull request will:**
- title

**Final test:**
- [x] local
- [x] server

**Screenshots**

### CODE REVIEW

**Comment by TheLocalPub** [comment]
This new feature.

How does the tagging work?
Tags now spawn randomly on abandon vehicles? Which we can spray paint over like before?

**Comment by Vdauphin** [comment]
Hello,

> Tags now spawn randomly on abandon vehicles?

When you left a vehicle behind you, ie when you exit a city and you enter it back, civilians will draw sentences on your vehicles

> Which we can spray paint over like before?

Yes, it is just an ACE feature, you can paint over it

Prefer open a discussion when you have question
Discussion is more searchable, and it will have more view

Cheers

**Comment by TheLocalPub** [comment]
Nice work. Thanks.
-  Sorry, about commenting here. I though here would be appropriate.

**Comment by Vdauphin** [comment]
No worries

**Pull request merged**
