### PR TITLE
Add: Save Slot Parameter

### PR DESCRIPTION
**Pull request by mrschick**
- Add: Mission Parameter to toggle loadout/position saving between connections (@mrschick).

**When merged this pull request will:**
- Add a mission parameter that allows selecting whether a player slot's current position and loadout should persist between connections.

**Final test:**
- [x] local
- [x] server

**Screenshots**
None applicable.

### CODE REVIEW

**Comment by Vdauphin** [comment]
Hello,

What will happen if player disconnect or lose connection when their vehicle is away of the main base/FOB?
May be disable vehicle persistency at the same time? But honestly it kill the core idea of H&M

Cheers

**Comment by mrschick** [comment]
Personally, that event is pretty rare when playing with stable mods.

The reason we implemented it in our mission is because we prefer not having to worry about a slot not spawning in the base, given that someone else may not have had the time to return before disconnecting.

True, I didn't consider vehicle persistency because our server reboots itself every 24h, respawning all vehicles anyway and replacing them as they were in the editor.

**Comment by Rad-Ezz** [comment]
Je suis du même avis, avoir un paramètre pour permettre de choisir la position et emplacement de joueurs, le fait d'avoir des bugs ou déconnexion, cela ne regarde que le serveur, mais au moins nous avons la possibilité de choisir pour cette option.
Des fois on se retrouve connecté dans des endroits impossible un autre jour car certains joueurs doivent se déconnecter pour partir.
et certains serveur ne reste pas ouvert 24h/24h pour l'option de restart !

Merci de bien vouloir au moins ce choix de déécision

**Comment by Rad-Ezz** [comment]
@mrschick 
So, has this option been integrated?

Thank you for your reply

**Comment by Vdauphin** [comment]
From a gameplay perspective it also completely break the ticket system as player can disconnect and connect again back to base in order to not been killed.
An alternative to this PR would be to give more granularity and consistency with other setting. As the setting is already available for respawn from FOB to base we can extend it by making the same interaction available but for Helo, helicopter, vehicle, player as I did for the respawn setting: https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/param.hpp#L83

Also when you exit a game you expect to come back to where you disconnect as you don't want to lose all your progression

@Rad-Ezz English only please.

**Comment by mrschick** [comment]
> From a gameplay perspective it also completely break the ticket system as player can disconnect and connect again back to base in order to not been killed.

One could also disconnect to let AI despawn and then reconnect to exfil.
Disconnects in general for gamey reasons are not a thing in our closely-knit group.

> we can extend it by making the same interaction available but for Helo, helicopter, vehicle, player

Not sure what you mean, which interaction?

> Also when you exit a game you expect to come back to where you disconnect as you don't want to lose all your progression

I guess that's subjective 🤷🏻‍♂️
Ultimately it's your call to make, I understand if it doesn't fit your intended way to play H&M 👍🏻

**Comment by Vdauphin** [comment]
> One could also disconnect to let AI despawn and then reconnect to exfil.

No because AI respawn at exact same position (at least for city) but yea patrol may move away after some times 

> Disconnects in general for gamey reasons are not a thing in our closely-knit group.

Sure but we need to think for all, giving granularity is the best to fit most group. When you play large group there is always that guy with bad internet connection which is losing it when you don't want

> Not sure what you mean, which interaction?

https://github.com/Vdauphin/HeartsAndMinds/pull/894
The "Re-deploy base" with the NATO flag on the screenshot from a FOB

> I guess that's subjective 🤷🏻‍♂️

Well most game have this feature, even A3 scenario are saved when you play them

**Comment by mrschick** [comment]
> The "Re-deploy base" with the NATO flag on the screenshot from a FOB

Ah, that one. I guess at that point people could also just force redeploy via the esc menu.

**Comment by Vdauphin** [comment]
Respawn button of esc menu? 
They will lose reputation, tickets and their dead body will stay in place

**Comment by mrschick** [comment]
I thought redeploy would do the same, makes sense that it wouldn't I guess.

**Review by Rad-Ezz — COMMENTED** [review]
i changed all lines codes, but doesn't work. a messsage's mistake appared

**Comment by mrschick** [comment]
What sort of error message?

**Comment by Rad-Ezz** [comment]
I must have made a small mistake, not so big which makes all the difference, it seems to me that it's good

**Pull request closed without merging**
