### PR TITLE
Update stringtable.xml: Add Simplified Chinese translation to new contents

### PR DESCRIPTION
**Pull request by GoldJohnKing**
- Add: Simplified Chinese translation to new contents. (@GoldJohnKing)
- FIX: Improve several Simplified Chinese translations. (@GoldJohnKing)

**When merged this pull request will:**
- Add Simplified Chinese translation to new contents.
- Improve several Simplified Chinese translations to better match the new contents.
- https://github.com/Vdauphin/HeartsAndMinds/issues/400

**Important:**
- Please see the part where I add "" and "".
- I've noticed that Original (English) and German translations does not match each other.
- Unfortunately, I do not read German, so I could only use Google Translation to "guess" the meanings.
- However, judging from Key ID, I bet there might be something wrong with either Original or German translation.
- Please check and let me know what these four refer to.

**Final test:**
- [x] local
- [x] server

### CODE REVIEW

**Comment by 1kuemmel1** [comment]
Hello @GoldJohnKing ,

> I've noticed that Original (English) and German translations does not match each other.
Unfortunately, I do not read German, so I could only use Google Translation to "guess" the meanings.

Yes and no. There are usually no word-to-word translations, as that would sometimes sound a bit strange in German. But I can assure you that the meaning is reflected in every case.

> -However, judging from Key ID, I bet there might be something wrong with either Original or German translation.

Could you please give me an example?

Anyway; Mistakes can happen to anyone, and I'm happy to patch them up. So if you have hints or suggestions, then always get out with it. 😃 

greetings

**Comment by Vdauphin** [comment]
> I've noticed that Original (English) and German translations does not match each other.

Also, this could happen when I add new feature and the German translation or other are not updated in the same time. Always trust the English one

**Comment by Vdauphin** [comment]
https://github.com/Vdauphin/HeartsAndMinds/blob/82a636dd0b3f6d84874b6a49a866c2c5616a9be8/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/stringtable.xml#L763-L784
```xml
            <!-- Begin: Translation might be confusing. -->
            <Key ID="STR_BTC_HAM_SIDE_CAPOFF_SURRENDER_DESC">
                <Original>Surrender the officer.</Original>
                <German>Nehmen Sie den Offizier gefangen.</German>
                <Chinesesimp>将这名军官囚禁起来。</Chinesesimp>
            </Key>
            <Key ID="STR_BTC_HAM_SIDE_CAPOFF_SURRENDER_TITLE">
                <Original>Surrender the officer</Original>
                <German>Offizier gefangen nehmen</German>
                <Chinesesimp>囚禁军官</Chinesesimp>
            </Key>
            <Key ID="STR_BTC_HAM_SIDE_CAPOFF_HANDCUFF_DESC">
                <Original>Handcuff the officer.</Original>
                <German>Legen Sie dem Offizier Handschellen an.</German>
                <Chinesesimp>给这名军官戴上手铐。</Chinesesimp>
            </Key>
            <Key ID="STR_BTC_HAM_SIDE_CAPOFF_HANDCUFF_TITLE">
                <Original>Handcuff the officer</Original>
                <German>Offizier gefangen nehmen</German>
                <Chinesesimp>把这名军官囚禁起来。</Chinesesimp>
            </Key>
            <!-- End: Translation might be confusing. -->
```
What is the issue here ?

Don't put comment directly, prefer issue creation or comment in the PR to talk about it so you don't have to commit again to remote it in case it is not necessary

Thanks you for your time :)

**Comment by GoldJohnKing** [comment]
> What is the issue here ?

The first two Key IDs and English translations are surrender and the last two are handcuff.
However, what Google translation gives me about the German translation is that 1,2,4 is about capture the office, only 3 (https://github.com/Vdauphin/HeartsAndMinds/blob/82a636dd0b3f6d84874b6a49a866c2c5616a9be8/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/stringtable.xml#L779) is about handcuff.

**Pull request merged**
