### PR TITLE
FIX: Sidemission: destroy underwater generator Script error

### PR DESCRIPTION
**Pull request by 1kuemmel1**
**When merged this pull request will:**
- fix a small script error in 'core/fnc/side/underwater_generator.sqf' (since https://github.com/Vdauphin/HeartsAndMinds/pull/383)

**Final test:**
- [x] local
- [x] server

**excerpt from the RPT log**
```
14:42:31 Error in expression <te_group;

_pos = getPosASL _generator;
leader _group setPosASL [_pos select 0, >
14:42:31   Error position: <leader _group setPosASL [_pos select 0, >
14:42:31   Error leader: Typ Array, erwartet Objekt,Gruppe,Team member
14:42:31 File E:\Dokumente\Arma 3\mpmissions\ArmA-OtherProjects\HeartsAndMinds\=BTC=co@30_Hearts_and_Minds.Altis\core\fnc\side\underwater_generator.sqf, line 61
```

### CODE REVIEW

**Comment by Vdauphin** [comment]
correct and also : 
```
C:\Users\Vivian\Documents\GitHub\HeartsAndMinds\=BTC=co@30_Hearts_and_Minds.Altis\core\fnc\mil\send.sqf:
   17  	case 0 : {
   18  		private ["_wp_0","_wp"];
   19: 		_group = [_pos,150,(3 + random 6),1] call btc_fnc_mil_create_group;
   20  		_group setVariable ["no_cache",true];
   21  		while {(count (waypoints _group)) > 0} do { deleteWaypoint ((waypoints _group) select 0); };
```
```

C:\Users\Vivian\Documents\GitHub\HeartsAndMinds\=BTC=co@30_Hearts_and_Minds.Altis\core\fnc\rep\call_militia.sqf:
   94  {
   95  	//INF
   96: 	_group = [_start_pos,50,(8 + random 6),1] call btc_fnc_mil_create_group;
   97  	_group setVariable ["no_cache",true];
   98  	while {(count (waypoints _group)) > 0} do { deleteWaypoint ((waypoints _group) select 0); };
```

Sorry!

**Comment by Vdauphin** [comment]
Do you have time to fix also those files ? If not I will fix it. Thanks to point this !

**Comment by 1kuemmel1** [comment]
Sorry, I didn't get any errors. Can you do this?

**Comment by Vdauphin** [comment]
yep!

**Pull request merged**
