### PR TITLE
Add: Grafity sentence

### PR DESCRIPTION
**Pull request by Vdauphin**
- Add: Gratify sentence (@Vdauphin).

**When merged this pull request will:**
- title
- https://github.com/Vdauphin/HeartsAndMinds/issues/400

**Final test:**
- [x] local
- [x] server

**Screenshots**

### CODE REVIEW

**Comment by GoldJohnKing** [comment]
Hi, does this support non-Latin characters like Chinese characters? I've noticed that the server always choose `Original` language, no matter what language is set in server's `basic.cfg` file, so does adding translation to `stringtable.xml` works?

Another question, would you please make it possible for players to print letter tags, just like naming a FOB?

Cheers!

**Comment by Vdauphin** [comment]
Hello,

> Hi, does this support non-Latin characters like Chinese characters? 

It doesn't works. BI doesn't provide the .paa for it 

> I've noticed that the server always choose Original language, no matter what language is set in server's basic.cfg file, so does adding translation to stringtable.xml works?

I tried a long time ago and it worked (https://github.com/Vdauphin/HeartsAndMinds/issues/400#issuecomment-342176892).

> Another question, would you please make it possible for players to print letter tags, just like naming a FOB?

This is not possible. We need each non-Latin characters in a .paa.
Sorry :/

Cheers!

**Comment by GoldJohnKing** [comment]
> We need each non-Latin characters in a .paa.

So there's no need to translate those phrases into Chinese? Or should we put Latin words in non-Latin languages' tags in stringtable.xml?

**Comment by Vdauphin** [comment]
> So there's no need to translate those phrases into Chinese?

Into chinese and non latin, it is useless

>  Or should we put Latin words in non-Latin languages' tags in stringtable.xml?

I don't see advantage to do it

**Pull request merged**
