### PR TITLE
Add: Task description is now localize client side

### PR DESCRIPTION
**Pull request by Vdauphin**
https://github.com/Vdauphin/HeartsAndMinds/issues/400#issuecomment-342176892

**When merged this pull request will:**
- Task description title and icon title are localize accordingly to client language
- `btc_fnc_task_create` create the task on server. When created ([`BIS_fnc_taskExists`](https://community.bistudio.com/wiki/BIS_fnc_taskExists)), now also, update  the description ([`BIS_fnc_setTask`](https://community.bistudio.com/wiki/BIS_fnc_setTask))  with the correct language of the client (So now, on a German dedicate server, English client and German client will have the correct localize  description). 
- side mission update due to this new behavior

Todo : 

- [x] replace by `_taskID`
- [x] btc intro disappear
- [x] test if hint is not show twice when more than one player is connected
- [x] test all side mission.
- [x] test final phase task.

**Final test:**
- [x] local
- [x] server

**Screenshots**
German dedicate server and French client:

### CODE REVIEW

**Comment by 1kuemmel1** [comment]
Really great! 👍 
I made a similar upgrade too. Just a bit different but the same results.

**Comment by Vdauphin** [comment]
Do not hesitate to share if you have a better solution :)

**Comment by 1kuemmel1** [comment]
> Do not hesitate to share if you have a better solution :)

Better ? I didn't think so 😄 
But you've been right: here you can take a look [Add-task_handling_client](https://github.com/1kuemmel1/HeartsAndMinds/commit/6d344293a401eef56a1bae794ab151dce2f6b982)

**Comment by Vdauphin** [comment]
I took a little look to your solution. I think my solution is a little simpler ^^ but thanks for the share!
My goal is to slowly leave BI handle task because BI task system is actually good and can handle multiple taks at the same time (somebody asked me this feature).

**Pull request merged**
