### PR TITLE
FIX: Prevent redeploy when carrying object

### PR DESCRIPTION
**Pull request by mrNo0b**
- FIX: Prevent redeploy when carrying object (@mrNo0b).

**When merged this pull request will:**
- title

**Final test:**
- [x] local
- [x] server

### CODE REVIEW

**Comment by mrNo0b** [comment]
this fix disables the option to teleport while carrying object, #839 prevents deploying the fob, its different.

**Comment by Vdauphin** [comment]
> is it possible to block all ACE and regular actions while carrying objects?
Do you have an example?
When you carry through ACE, others interaction are block if !i remeber
When carrying through H&M, we need to use btc_log_placing for H&M interaction but for ACE it will be not easy

I believe more in the full use of ACE dragging/carry and drop H&M placing but then we will have a lake of accuracy during placement...

**Comment by mrNo0b** [comment]
It would be better to block all player actions inside `place.sqf` itself instead of using `btc_log_placing` in other parts of the mission because it will be easier to maintain

**Comment by Vdauphin** [comment]
If you have a solution, PR it

**Pull request merged**
