### PR TITLE
Add: Remove double actions (orders to civilians)

### PR DESCRIPTION
**Pull request by 1kuemmel1**
**When merged this pull request will:**
- Remove the "Get Down!" and "Go Away!" actions from ACE³-interaction menu (see screenshots below)

**Final test:**
- [x] local
- [x] server

**Screenshots**
OLD:
civ_actions_old
NEW:
civ_actions_new

### CODE REVIEW

**Comment by Vdauphin** [comment]
Hello, sadly I am not sure if this approach will work on all class name (see https://github.com/acemod/ACE3/issues/2576#issuecomment-156048545). Looks like some mods are not compatible with CBA XEH (https://github.com/Giallustio/HeartsAndMinds/commit/33323afc9aa68596118785baf58c381c5d577605#diff-92e95921cfc9c8acde69602348016377).

I don't have a lot of knowledge on this. If this work on dedicate with all mod supported by the H&M, I will accept it.

If it is not working, use the Giallustio approach (https://github.com/Vdauphin/HeartsAndMinds/blob/master_daily/=BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf)

**Comment by 1kuemmel1** [comment]
Oh, I didn't know about this.


> If this work on dedicate with all mod supported by the H&M, I will accept it.

Give me some time 😆. I will test.

**Comment by 1kuemmel1** [comment]
Hiho here is a first review/feedback. 
(All mods tested local and on server, all mods are up to date - 03. Dec.17)
- [x] [CUP Units](http://steamcommunity.com/sharedfiles/filedetails/?id=497661914) (include [CUP Weapons](http://steamcommunity.com/workshop/filedetails/?id=497660133) and [CUP Vehicles](http://steamcommunity.com/sharedfiles/filedetails/?id=541888371)) = **No interactions available at all (except ACE's)**

- [x] [=BTC= Militia mod](http://giallustio.altervista.org/militia.html)  = **No interactions available at all (except ACE's)**

- [x] [Project OPFOR](http://steamcommunity.com/sharedfiles/filedetails/?id=735566597) = **Works fine**

- [x] [CAF_AG1.5](http://steamcommunity.com/sharedfiles/filedetails/?id=664276003) =  **Works fine**

**Comment by Vdauphin** [comment]
Good job!
When you say **No interactions available at all** you mean : 
No "Get Down!" and "Go Away!" actions from ACE³-interaction and no "Civil Orders" actions from H&M-interaction ?

**Comment by Vdauphin** [comment]
[This](https://github.com/Vdauphin/HeartsAndMinds/pull/440) will fix the **No interactions available at all** problem :)

**Comment by 1kuemmel1** [comment]
Update list.

*My conclusion so far: do not implement, because unfortunately not all mods are supported.*

**Comment by Vdauphin** [comment]
Basically it not working because `Civilian` is not use by some mod in parents class ... I think this would works if you use  `CAManBase` or `Man` and then use https://github.com/Vdauphin/HeartsAndMinds/blob/master_daily/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/eh/unit_init.sqf and do a if side == civilian removeinteraction

Or use the add_actions file ad said previously 

See you!

**Comment by 1kuemmel1** [comment]
> Basically it not working because Civilian is not use by some mod in parents class ... I think this would works if you use CAManBase or Man...
This is a good approach!
I will take a look at these the next days.

**Comment by Vdauphin** [comment]
Check before if mods use `CAManBase` parent in config to avoid waste of your time

**Comment by 1kuemmel1** [comment]
Please remember; you need #440 for this.

**Comment by 1kuemmel1** [comment]
update: now it´s include the fix from #440

**Comment by Vdauphin** [comment]
Here your goal is to remove the action. So why not just add in [/core/fnc/int/add_actions.sqf#L78](https://github.com/Vdauphin/HeartsAndMinds/blob/master_daily/=BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf#L78) : 
```
{
	//remove "get down" order
	[_x, 0,["ACE_MainActions","ACE_GetDown"]] call ace_interact_menu_fnc_removeActionFromClass;

	//remove "go away" order
	[_x, 0,["ACE_MainActions","ACE_SendAway"]] call ace_interact_menu_fnc_removeActionFromClass;
} forEach btc_civ_type_units;
```

Just 4 lines of code, nothing complicated. I am agree the CBA `Extended_InitPost_EventHandlers` is really powerfull but not necessary to do what you want to do. Stay simple.

If you want to takes advantage of  CBA `Extended_InitPost_EventHandlers` do it in a seperate pull request and transfer all actions ([add_actions.sqf#L53-L77](https://github.com/Vdauphin/HeartsAndMinds/blob/master_daily/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf#L53-L77)) and call of `btc_fnc_mil_unit_create`, `btc_fnc_civ_unit_create` in it. Like Giallustio did in the past : https://github.com/Giallustio/HeartsAndMinds/commit/33323afc9aa68596118785baf58c381c5d577605#diff-92e95921cfc9c8acde69602348016377

**Pull request merged**
