### PR TITLE
Add: CBA and ACE3 mod only dependency

### PR DESCRIPTION
**Pull request by Vdauphin**
**When merged this pull request will:**
- Add a `mission.sqm` without RHS dependency (Need CBA, ACE3).
   - 4 light armored vehicle, 2 vehicles with armor and 1 tank : 
       - HUMVEE are replaced by Prowler for their light armor (Looks better than offroad. Offroads are also used by OPFOR).
       - RG33L are replaced by M-ATV for their good armor against light weapons (thermal vision).
   
- Rename other mission.sqm (Need CBA, ACE3, RHSUS) by : 
   - `mission_RHSUS_Altis.sqm`
   - `mission_RHSUS_Tanoa.sqm`

**Final test:**
- [x] local
- [x] server

**Screenshots**

### CODE REVIEW

**Comment by storrgie** [comment]
Will the RHS content be optionally available going forward, or will H&M now move away from RHS completely?

**Comment by Vdauphin** [comment]
Basically you will have 3 versions of the H&M: 
- two on Altis : 
     - first need CBA and ACE
     - second need CBA, ACE and RHSUS
- one on Tanoa : 
    - need CBA, ACE and RHSUS

So, it is a let's do both!

**Comment by bux** [comment]
Might need changes:

https://github.com/Vdauphin/HeartsAndMinds/blob/Add-ACE_only_sqm/=BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/add_veh.sqf#L8

https://github.com/Vdauphin/HeartsAndMinds/blob/Add-ACE_only_sqm/=BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf

Not sure here:
https://github.com/Vdauphin/HeartsAndMinds/blob/Add-ACE_only_sqm/=BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf#L450
_There's also a `_03_` variant_

**Comment by Vdauphin** [comment]
> https://github.com/Vdauphin/HeartsAndMinds/blob/Add-ACE_only_sqm/=BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/add_veh.sqf#L8
>https://github.com/Vdauphin/HeartsAndMinds/blob/Add-ACE_only_sqm/=BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf

If you are talking about the `!(typeof _vehicle isEqualTo "RHS_UH1Y_d")` check. I put it because the FRIES system looks really ugly on this particular helicopter. 


I am agree this helicopter should be change for an other one but I don't want to denaturate the initial works.


> Not sure here:
> https://github.com/Vdauphin/HeartsAndMinds/blob/Add-ACE_only_sqm/=BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf#L450
> _There's also a `_03_` variant_



https://github.com/Vdauphin/HeartsAndMinds/blob/Add-ACE_only_sqm/=BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf#L456-L464 : This part of the code give the possibility to admin to use helicopter which does not match the weight check after:
https://github.com/Vdauphin/HeartsAndMinds/blob/Add-ACE_only_sqm/=BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf#L438-L454
This last part handle the lifting depend on the config `"slingLoadMaxCargoMass"` (https://forums.bistudio.com/forums/topic/165948-mp-btc-hearts-and-minds/?page=34&tab=comments#comment-3249459).

I agree, the first part could be clean up due to the second part but in a different PR when time is found :)

**Pull request merged**
