### PR TITLE
Add: integration of ACE3 mine detector

### PR DESCRIPTION
**Pull request by Vdauphin**
https://github.com/acemod/ACE3/issues/4296
https://github.com/Vdauphin/HeartsAndMinds/issues/184

this do : 
- create ied around a suspect object (like wreck)
  - use createSimpleObject for wreck to avoid performance issue https://community.bistudio.com/wiki/createSimpleObject
  - create IED around wreck supporting mine detector
- [x] improve code
- [x] IED fly sometimes
- [x] update documentation 
- [x] remove ied check ACE3 interaction
- [x] remove engineer needed in mission parameter or take a look in ACE3 to see if engineer have bigger chance to disarm Or ace_explosivesRequireSpecialist
- [x] database compatible
- [x] remove debug

Final test :
- [x] local
- [x] server

http://steamcommunity.com/sharedfiles/filedetails/?id=773214532

### CODE REVIEW

**Comment by Breech99** [comment]
In the IED create the random spawn location of the IED places it too out in the open next to the wreck object and piles. Seems too easy to spot, locate and disarm.  The code shows random position? 
Was it too difficult for the player to see ACE disarm IED icon if placed directly underneath the immovable wreck simple objects spawned?  
_ied = createMine [selectRandom btc_type_ieds_ace,[_pos select 0, _pos select 1, -0.07],[],2];

**Comment by Vdauphin** [comment]
> Seems too easy to spot, locate and disarm.

I can use some mine harder to locate and also I am spawning mine slitly underground  **-0.07**
`_ied = createMine [selectRandom btc_type_ieds_ace,[_pos select 0, _pos select 1, -0.07],[],2];`

>  The code is random position? 

Yes the code is random position.

> Was it too difficult for the player to see ACE disarm IED icon if placed directly underneath the immovable wreck simple objects spawned in earlier version of code?

I did it but if I remember, I could not interact with IED in this configuration :(

> Possibly have area of effect and place multiple IED at spawn location? 

Bad idea to have IED has you said it will add performance effect ...

**Comment by Vdauphin** [comment]
Perfect ! 
This pull is reaching the final phase. So it is time for me to test it in my server. If no big issue appear, other commits should be only little fix and tweak.

**Comment by Breech99** [comment]
I find ACE3 ied easier to disarm. The regular IED are blowing up at far greater range and have no user interaction when you changed in ticket  0c58870 . leaving it ["ACE_IEDLandBig_Range","ACE_IEDLandSmall_Range"]; finds  its  working in  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf

**Pull request merged**
